POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "email":"ADMIN@admin.fr",
    "password":"admin"  ,
    "role":"ADMIN" 
}
####


PUT http://localhost:5000/users/d80b74a7-0dbe-4948-aa81-c020846d792b

{
    "email":"admin@admin.fr",
    "role":"ADMIN" 
}
###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email":"ADMIN@admin.fr",
    "password":"admin"  ,
    "role":"ADMIN" 
}

###
GET http://localhost:5000/users/
###
###
GET http://localhost:5000/users/
###
PUT http://localhost:5000/users/9f3e17a7-ae8a-4488-89ce-5986f4b7c56e
Content-Type: :application/json

{
    "email":"admin@admin.fr",
    "role":"ADMIN" ,
    "username":"julien"
}



###
GET https://api.wildcodeschool.com/api/v3/notifications
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1aWQiOjI4ODk3LCJtaWQiOm51bGwsInQiOiIyMDIxMDcyMjA3NTk0OCJ9.SyWmjNj2TAxmaqC7rgLWiPvLGwVFbdAEsaZtSmGRs-8